use_frameworks!
platform :ios, '10.0'

target 'GLTFSceneKitLoader_Example' do
  pod 'GLTFSceneKitLoader', :path => '../'

  target 'GLTFSceneKitLoader_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'ModelMapper'
  end
  
  
  
  
end
