use_frameworks!

target 'GLTFSceneKitLoader_Example' do
  pod 'GLTFSceneKitLoader', :path => '../'

  target 'GLTFSceneKitLoader_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
